apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boardgame-app
  namespace: argocd   # Argo CD is installed in this ns
spec:
  project: default

  source:
    repoURL: 'https://github.com/Sivakrishnachekuri/Boardgame-CICD.git' # your GitHub repo
    targetRevision: main   # branch name
    path: .                # path where deployment-service.yaml exists

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boardgame   # app will be deployed here

  syncPolicy:
    automated:             # auto sync changes from Git
      prune: true          # remove old resources
      selfHeal: true       # fix drift if someone changes cluster directly
